### ISSUE TITLE
Redo dask pod labels

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-data/pangeo-binder#147]
In #145 I added the username to the Dask Gateway pods as a label like.

```
Labels:
  jupyterhub/username: <username here>
```

I just discovered that jupyterhub does something similar to their pods with Annotations

```yaml
Name:                 jupyter-tomaugspurger-2dpangeo-2dbinder-2dtest-2dga6arn36
Namespace:            prod
Priority:             0
Priority Class Name:  prod-default-priority
Node:                 gke-binder-user-pool-3a8deb5e-5v53/10.128.0.76
Start Time:           Fri, 24 Apr 2020 14:02:59 -0500
Labels:               app=jupyterhub
                      chart=jupyterhub-0.9.0-beta.4
                      component=singleuser-server
                      heritage=jupyterhub
                      hub.jupyter.org/network-access-hub=true
                      release=prod
Annotations:          hub.jupyter.org/username: tomaugspurger-pangeo-binder-test-ga6arn36
```

It's probably best to align our method to jupyterhubs.
