### ISSUE TITLE
Increase quota for larger tutorials

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo-binder#40]
When giving a tutorial today, @jcrist ran into the 100 user-per-repository quota set by default in binderhub.  We may want to increase this quota in the future if we want to support larger tutorials.

```yaml
binderhub:
  config:
      per_repo_quota: 100
```

See also: https://github.com/pangeo-data/pangeo/issues/440#issuecomment-479656247
